### Exercise_Week08_Python
* import necessary libraries in the box below

### Question 01
Create a NumPy array from [-60,-59,...,-1,0,1,2,3,...,60].

* Replace all odd numbers with -1

In [1]:
import numpy as np
array_1 = np.arange(-59,60,2)
array_1

array([-59, -57, -55, -53, -51, -49, -47, -45, -43, -41, -39, -37, -35,
       -33, -31, -29, -27, -25, -23, -21, -19, -17, -15, -13, -11,  -9,
        -7,  -5,  -3,  -1,   1,   3,   5,   7,   9,  11,  13,  15,  17,
        19,  21,  23,  25,  27,  29,  31,  33,  35,  37,  39,  41,  43,
        45,  47,  49,  51,  53,  55,  57,  59])

### Question 02
With np.where, find the positions of:

* Find Elements in x where its value is more than its corresponding element in y.
* Elements in x where its value is equals to its corresponding element in y.

In [4]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 74, 29, 55, 4, 37, 18])

In [14]:
array_2 = x[x[:]>y[:]]
array_2

array([64, 86, 55, 81, 79, 90, 89])

In [29]:
array_equal = x[x[:]==y[:]]
array_equal

array([21, 74])

### Question 03

Create a random 7×24 matrix representing hourly temperatures for one week.

(7 days, 24 Hour)

* Find the hour with the highest average temperature.
* Find the day with the highest average temperature.
* Compute the difference between max and min temperature.

In [61]:
array_03 = np.random.randint(-100,100,(7,24))
max_temp = np.max(array_03)
max_position = np.unravel_index(np.argmax(array_03),array_03.shape)
day_of_max = max_position[0]
day_of_max

np.int64(1)

In [59]:
hour_of_max = max_position[1]
hour_of_max

np.int64(12)

In [62]:
min_temp = np.min(array_03)
min_temp

np.int32(-99)

In [63]:
max_temp

np.int32(99)

In [64]:
diff_temp = max_temp - min_temp
diff_temp

np.int32(198)

### Question 04
Create a 30×5 matrix (30 students, 5 courses).

* Compute each student's average.
* Compute each course average.
* Identify students who scored above 15 in at least 3 courses.
* Find the hardest course (with the loest scores)

In [71]:
array_04 = np.random.randint(0,21,(30,5))
array_04

array([[19, 10, 15,  5, 18],
       [19, 15, 18, 17, 16],
       [10,  1,  4,  5, 17],
       [20,  9,  2, 11,  8],
       [ 5, 15, 20,  0,  9],
       [19, 18, 10,  1, 16],
       [15, 15,  9,  0,  7],
       [ 7, 20, 17,  9,  8],
       [13, 16,  4,  8,  7],
       [20, 17, 18,  7,  3],
       [14,  6, 17, 20,  2],
       [ 0,  2,  9,  1, 16],
       [ 3,  7,  0,  3,  5],
       [ 7,  4, 18,  4, 16],
       [ 3, 18, 15, 11,  2],
       [ 3, 14,  4,  8, 12],
       [ 8, 12, 14, 20, 14],
       [ 6,  4,  2,  2, 15],
       [17, 12,  4, 12,  1],
       [ 7, 18, 16, 12, 12],
       [ 0,  3,  5, 17, 17],
       [17, 16,  4,  4, 19],
       [13,  0,  4,  6, 14],
       [ 6,  2, 16, 18, 20],
       [ 5,  8,  0,  0, 19],
       [ 7, 15, 18,  2, 10],
       [15, 12,  5,  1,  2],
       [10,  4, 19, 10,  6],
       [ 5,  9,  8,  6, 15],
       [ 1,  4, 19, 10, 16]], dtype=int32)

In [68]:
st_mean = np.mean(array_04,axis=1)
st_mean


array([ 8. ,  9.4,  7.8, 11.8,  8. ,  1.6, 10.2,  7.4,  6.6, 11.2, 10.2,
        7. ,  8. ,  6.2,  8.6,  8.6, 10.6,  4.6,  9.4, 12.4, 11.6,  7.4,
        7.2,  9.4, 14.6,  8.4, 12.2,  6.8, 14.6, 12. ])

In [70]:
course_mean = np.mean(array_04,axis=0)
course_mean

array([ 9.23333333,  8.06666667,  9.96666667,  7.23333333, 10.8       ])

In [72]:
score_above_15 = array_04 > 15
count_above_15 = np.sum(score_above_15,axis=1)
st_with_high_score = np.where(count_above_15 >= 3)[0]
st_with_high_score

array([ 1,  5,  9, 21, 23])

In [73]:
course_mean = np.mean(array_04, axis=0)
hardest_course = np.argmin(course_mean)
hardest_course

np.int64(3)

### Question 05

Generate two 1D arrays for 12 months:

Income array (values between 5000–15000)

Expenses array (values between 3000–12000)

* Compute monthly profit.
* Find the most profitable month.
* Identify loss months (profit < 0).

In [19]:

month = np.arange(1,13)
income = np.random.randint(5000,15001,12)
expenses = np.random.randint(3000,12001,size=(1,12))
profit = income - expenses
print(income,expenses,profit)

[ 7553 14339 12193  5961 14896  7578 11359  8255  7837  9607 10665 14392] [[ 7120  6162  3923  9866 11755  9569  6303  5240 10760  6312  6469  6584]] [[  433  8177  8270 -3905  3141 -1991  5056  3015 -2923  3295  4196  7808]]


In [20]:
most_profitable_month = np.argmax(profit)
most_profitable_month 


np.int64(2)

In [21]:
loss_months = np.where(profit<0)[0]+1
loss_months

array([1, 1, 1])

### Question 06

Create a Series with 30 different product names as indexes

and enter random numbers (sales) as values.

* Find best-selling product.
* Compute percentage share of each product.
* Remove products below average sales.

In [34]:
import pandas as pd
products_name = pd.Series(["Smart Watch","Wireless Earbuds","Bluetooth Speaker","Gaming Laptop","Mechanical Keyboard",
                          "Optical Mouse","LED Monitor","Power Bank","Fitness Tracker","Digital Camera","Tablet Pro" 
                          ,"Smart phoneX","Noise Cancelling","Headphones","Portable Charger","Smart TV","External Hard Drive",
                          "USB Flash Drive","Action Camera","Electric Toothbrush","Coffee Maker","Air Fryer","Vacuum Cleaner","Water Bottle","Office Chair","Back pack","Running Shoes","Sun glasses","Printer","Router"])
sales_series = pd.Series(np.random.randint(100,1000,30),index=products_name)
sales_series

Smart Watch            309
Wireless Earbuds       846
Bluetooth Speaker      515
Gaming Laptop          276
Mechanical Keyboard    187
Optical Mouse          772
LED Monitor            938
Power Bank             514
Fitness Tracker        442
Digital Camera         298
Tablet Pro             909
Smart phoneX           409
Noise Cancelling       635
Headphones             645
Portable Charger       469
Smart TV               701
External Hard Drive    782
USB Flash Drive        714
Action Camera          892
Electric Toothbrush    659
Coffee Maker           384
Air Fryer              138
Vacuum Cleaner         888
Water Bottle           117
Office Chair           627
Back pack              543
Running Shoes          936
Sun glasses            833
Printer                159
Router                 749
dtype: int32

In [37]:
best_selling = sales_series.idxmax()
best_selling

'LED Monitor'

In [38]:
percentage_share = (sales_series / sales_series.sum()) * 100
percentage_share 


Smart Watch            1.787574
Wireless Earbuds       4.894134
Bluetooth Speaker      2.979290
Gaming Laptop          1.596668
Mechanical Keyboard    1.081800
Optical Mouse          4.466042
LED Monitor            5.426357
Power Bank             2.973505
Fitness Tracker        2.556983
Digital Camera         1.723938
Tablet Pro             5.258591
Smart phoneX           2.366077
Noise Cancelling       3.673493
Headphones             3.731343
Portable Charger       2.713178
Smart TV               4.055305
External Hard Drive    4.523892
USB Flash Drive        4.130510
Action Camera          5.160245
Electric Toothbrush    3.812334
Coffee Maker           2.221451
Air Fryer              0.798334
Vacuum Cleaner         5.137105
Water Bottle           0.676848
Office Chair           3.627213
Back pack              3.141270
Running Shoes          5.414787
Sun glasses            4.818929
Printer                0.919820
Router                 4.332986
dtype: float64

In [40]:
average_sales = sales_series.mean()
above_avg = sales_series[sales_series >= average_sales]
above_avg

Wireless Earbuds       846
Optical Mouse          772
LED Monitor            938
Tablet Pro             909
Noise Cancelling       635
Headphones             645
Smart TV               701
External Hard Drive    782
USB Flash Drive        714
Action Camera          892
Electric Toothbrush    659
Vacuum Cleaner         888
Office Chair           627
Running Shoes          936
Sun glasses            833
Router                 749
dtype: int32

### Question 07

Create a Series of 100 student with GPA (values between 8 and 20).

Change index of the series with student names.

* Find top 20% Students and print their names.
* Label students above 17 as "Excellent".

In [41]:
gpa_values = np.random.uniform(8, 20, 100)
student_names = [f"Student_{i}" for i in range(1, 101)]
gpa = pd.Series(gpa_values, index=student_names)
gpa

Student_1      13.625923
Student_2      15.859521
Student_3       8.218423
Student_4      18.423190
Student_5      12.916700
                 ...    
Student_96     13.574956
Student_97     15.911779
Student_98     17.591083
Student_99      8.757806
Student_100    11.731076
Length: 100, dtype: float64

In [42]:
labels = pd.Series("Normal", index=gpa.index)
labels[gpa > 17] = "Excellent"
labels

Student_1         Normal
Student_2         Normal
Student_3         Normal
Student_4      Excellent
Student_5         Normal
                 ...    
Student_96        Normal
Student_97        Normal
Student_98     Excellent
Student_99        Normal
Student_100       Normal
Length: 100, dtype: object

### Question 08

Create a Series of 50 people birthday year (1925 to 2025)

and set indexes with their gender (random Female/Male).

then, separate these 50 pople into 6 different series based on their generation:

* Alpha: Born 2013–2025.
* Z: Born 1997–2012 (Ages 14–29).
* Millennials: Born 1981–1996 (Ages 30–45).
* X: Born 1965–1980 (Ages 46–61).
* Baby Boomers: Born 1946–1964 (Ages 62–80).
* Silent: Born 1925–1945 (Ages 81–101). 

Finally, print number of Female and Male popele in each generation.

In [43]:
birth_years = np.random.randint(1925, 2026, 50)
genders = np.random.choice(["Female", "Male"], 50)
people = pd.Series(birth_years, index=genders)
people

Female    1986
Female    1928
Female    1938
Male      1966
Male      2007
Male      1925
Male      1971
Female    1967
Male      1984
Female    1972
Male      2001
Female    1943
Male      1926
Male      1935
Male      2016
Male      1970
Male      1972
Female    1994
Male      1979
Female    1982
Male      1942
Female    2020
Female    2010
Female    1935
Male      2016
Male      2004
Male      2001
Female    1936
Female    2005
Female    2000
Female    1975
Female    2023
Male      1951
Male      1963
Male      2009
Male      1942
Female    1977
Male      1960
Male      2023
Male      2024
Female    1936
Female    2021
Female    1989
Male      1951
Male      1980
Male      1983
Female    1958
Female    1992
Male      1996
Female    2004
dtype: int32

In [45]:
def generation(year):
    if 2013 <= year <= 2025:
        return "Alpha"
    elif 1997 <= year <= 2012:
        return "Gen Z"
    elif 1981 <= year <= 1996:
        return "Millennials"
    elif 1965 <= year <= 1980:
        return "Gen X"
    elif 1946 <= year <= 1964:
        return "Baby Boomers"
    else:
        return "Silent"

generations = people.apply(generation)
result = pd.crosstab(generations, people.index)
result

col_0         Female  Male
row_0                     
Alpha              3     4
Baby Boomers       1     4
Gen X              4     6
Gen Z              4     5
Millennials        5     3
Silent             6     5