### Question 00
import necessary libraries in the box below

In [ ]:
import ___ as ___

### Question 01
Create a NumPy array from [1,2,3, ..., 12].

In [5]:
import numpy as np
array_01 = np.arange(1,13)
array_01

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Question 02
Print the type of array array_01

In [9]:
print((array_01).dtype)

int64


### Question 03
Reshape array_01 into 3 x 4 matrix.

In [10]:
array_03 = array_01.reshape(3,4)
array_03

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Question 04
Get the length of the array_03.

In [12]:
print(array_03.size)

12


### Question 05
Print the second element of the second row in array_03.

In [13]:
print(array_03[2,2])

11


### Question 06
Multiply all elements of array_03 by 2.

In [14]:
array_06 =array_03*2
array_06

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

### Question 07
Add 5 to all elements of array_06.

In [15]:
print(array_06 +5)

[[ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


### Question 07
Create an array of 18 zeros.

In [16]:
array_07 = np.zeros(18)
array_07

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

### Question 08
Create an array of 20 fours.

In [18]:
array_08 = np.ones(20) * 4
array_08

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4.])

### Question 09
Create numbers from 0 to 20.

In [21]:
array_09 = np.arange(20)
array_09

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Question 10
Create 24 random numbers between 0 and 1.
Then, Reshape it into matrix with 6 rows.

In [54]:
array_10 = np.random.uniform(0,1,24)
array_10 = array_10.reshape(6,4)
array_10

array([[0.18285329, 0.62938146, 0.13261583, 0.75568472],
       [0.88485049, 0.23583134, 0.65380431, 0.62624571],
       [0.4048349 , 0.41375503, 0.3691661 , 0.68279629],
       [0.27698137, 0.71162624, 0.9014173 , 0.37691186],
       [0.5891944 , 0.29362513, 0.95119487, 0.88478897],
       [0.42459177, 0.30707027, 0.75546325, 0.92579665]])

### Question 11
Convert array_08 to String type.

In [36]:
array_11 = array_08.astype(dtype=str)
array_11

array(['4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0'], dtype='<U32')

### Question 12
Find sum of all rows in array_11

In [41]:
array_12 = array_11.astype(dtype=float)
print(array_12.sum())

80.0


### Question 13
Find mean of elements of array_10 'in' each row.

In [46]:
array_14 = array_10.astype(dtype=float)

print(array_14.mean(axis = 0))

[0.59434467 0.486428   0.67081447 0.58762755]


### Question 14
Reverse the array_10.

In [80]:
print(np.flip(array_10))

[[0.92579665 0.75546325 0.42459177 0.30707027]
 [0.95119487 0.88478897 0.5891944  0.29362513]
 [0.9014173  0.71162624 0.37691186 0.27698137]
 [0.68279629 0.41375503 0.4048349  0.3691661 ]
 [0.88485049 0.65380431 0.62624571 0.23583134]
 [0.75568472 0.62938146 0.18285329 0.13261583]]


### Question 15
Add array [1,2,3,4,5,6] to array_10.

In [52]:
array_15 = np.array([1,2,3,4,5,6]).reshape(6,1)
print(array_10+array_15)

[[1.9993192  1.10488506 1.52719499 1.90733226]
 [2.97098265 2.33814635 2.53491217 2.45239264]
 [3.82837628 3.5907551  3.22690308 3.74982882]
 [4.10683511 4.98037564 4.99774765 4.44230391]
 [5.00442077 5.25626455 5.92583708 5.24039177]
 [6.65613404 6.64814132 6.81229188 6.73351592]]


### Question 16
Print odd column of array_10

In [57]:
print(array_10[::2])

[[0.18285329 0.62938146 0.13261583 0.75568472]
 [0.4048349  0.41375503 0.3691661  0.68279629]
 [0.5891944  0.29362513 0.95119487 0.88478897]]


### Question 17
Create 3x3 zeros matrix.

In [58]:
array_17 = np.zeros((3,3))
array_17

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Question 18
Sort the array_10.

In [62]:

print(np.sort(array_10))

[[0.13261583 0.18285329 0.62938146 0.75568472]
 [0.23583134 0.62624571 0.65380431 0.88485049]
 [0.3691661  0.4048349  0.41375503 0.68279629]
 [0.27698137 0.37691186 0.71162624 0.9014173 ]
 [0.29362513 0.5891944  0.88478897 0.95119487]
 [0.30707027 0.42459177 0.75546325 0.92579665]]


### Question 19
Transpose the array_10 

In [63]:
print(array_10.T)

[[0.13261583 0.23583134 0.3691661  0.27698137 0.29362513 0.30707027]
 [0.18285329 0.62624571 0.4048349  0.37691186 0.5891944  0.42459177]
 [0.62938146 0.65380431 0.41375503 0.71162624 0.88478897 0.75546325]
 [0.75568472 0.88485049 0.68279629 0.9014173  0.95119487 0.92579665]]


### Question 20
Create even numbers from 11 to 56.

In [76]:
array_20 = np.arange(11,56)
even_number=[x for x in array_20 if x % 2==0]
even_number=np.array(even_number)
even_number

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52, 54])